version: '3'

services:
  mumble-server:
    build:
       context: .
       dockerfile: ./Dockerfile
       args:
        - adress_mumble_server=${ADRESS_MUMBLE_SERVER}
        - port_mumble_server=${PORT_MUMBLE_SERVER}
    container_name: ${CONTAINER_MUMBLE_SERVER}
    restart: unless-stopped
    ports:
      - "${PORT_MUMBLE_SERVER}:${PORT_MUMBLE_SERVER}"
      - "${PORT_MUMBLE_SERVER}:${PORT_MUMBLE_SERVER}/udp"
    environment:
      - TZ=UTC
      - VIRTUAL_HOST= ${DOMAINS}
      - LETSENCRYPT_HOST= ${DOMAINS}
      - LETSENCRYPT_EMAIL= ${LETSENCRYPT_EMAIL}

networks:
    default:
       external:
         name: ${NETWORK}
