version: '3'

services:
  mumble-server:
    build:
       context: .
       dockerfile: ./Dockerfile
       args:
        - adress_mumble_server=${adress_mumble_server}
        - port_mumble_server=${port_mumble_server}
        - MUMBLE_serverpassword=${MUMBLE_serverpassword}
        - name_mumble_server=${name_mumble_server}
        - MUMBLE_REGISTERNAME=${MUMBLE_REGISTERNAME}
    container_name: ${CONTAINER_MUMBLE_SERVER}
    restart: unless-stopped
    ports:
      - "${port_mumble_server}:${port_mumble_server}"
      - "${port_mumble_server}:${port_mumble_server}/udp"
    environment:
      - TZ=UTC
      - VIRTUAL_HOST= ${DOMAINS}
      - LETSENCRYPT_HOST= ${DOMAINS}
      - LETSENCRYPT_EMAIL= ${LETSENCRYPT_EMAIL}

networks:
    default:
       external:
         name: ${NETWORK}
